version: 2

multi-ecosystem-groups:
  plugin:
    schedule:
      interval: weekly
    assignees: [umireon]

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    multi-ecosystem-group: plugin
    patterns: ["*"]

  - package-ecosystem: npm
    directory: /pages
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@types/node"
        versions: ["*"]
    multi-ecosystem-group: plugin
    patterns: ["*"]
