# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Set up macOS Code Signing
description: Configure code signing for macOS.

# file: .github/actions/setup-macos-codesigning/action.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# version: 1.1.0
# date: 2026-03-30

inputs:
  MACOS_SIGNING_APPLICATION_IDENTITY:
    description: Application Identity for code signing.
    required: true
  MACOS_SIGNING_CERT:
    description: Base64 encoded .p12 certificate.
    required: true
  MACOS_SIGNING_CERT_PASSWORD:
    description: Password for the .p12 certificate.
    required: true

outputs:
  CODESIGN_TEAM:
    description: The Team ID.
    value: ${{ steps.extract.outputs.CODESIGN_TEAM }}

runs:
  using: composite
  steps:
    - name: Extract Codesign Identity
      id: extract
      shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
      env:
        MACOS_SIGNING_APPLICATION_IDENTITY: '${{ inputs.MACOS_SIGNING_APPLICATION_IDENTITY }}'
      run: |
        CODESIGN_TEAM="$(awk -F'[()]' '{ print $2 }' <<< "$MACOS_SIGNING_APPLICATION_IDENTITY")"

        if [[ -z "$CODESIGN_TEAM" ]]; then
          echo "Error: Failed to extract Team ID from MACOS_SIGNING_APPLICATION_IDENTITY" >&2
          exit 1
        fi

        printf 'CODESIGN_TEAM=%s\n' "$CODESIGN_TEAM" >> "$GITHUB_OUTPUT"

    - name: Import Signing Certificate
      shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
      env:
        MACOS_SIGNING_CERT: '${{ inputs.MACOS_SIGNING_CERT }}'
        MACOS_SIGNING_CERT_PASSWORD: '${{ inputs.MACOS_SIGNING_CERT_PASSWORD }}'
      run: |
        KEYCHAIN_DIR="$(mktemp -d -p "$RUNNER_TEMP" setup-macos-codesigning.XXXXXXXXXX)"
        KEYCHAIN_DB="$KEYCHAIN_DIR/app-signing.keychain-db"
        KEYCHAIN_PASSWORD="$(openssl rand -base64 32)"

        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_DB"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_DB"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_DB"

        security default-keychain -s "$KEYCHAIN_DB"

        base64 --decode <<< "$MACOS_SIGNING_CERT" > "$KEYCHAIN_DIR/certificate.p12"
        security import "$KEYCHAIN_DIR/certificate.p12" -k "$KEYCHAIN_DB" -P "$MACOS_SIGNING_CERT_PASSWORD" -T /usr/bin/codesign -T /usr/bin/productbuild
        rm "$KEYCHAIN_DIR/certificate.p12"

        security set-key-partition-list -S "apple-tool:,apple:,codesign:" -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_DB"
