version = 1

# Configuration files
[[annotations]]
path = [
    ".gitignore",
    ".ncurc.json",
    ".node-version",
    ".prettierrc",
    "astro.config.mjs",
    "package-lock.json",
    "package.json",
    "tsconfig.json",
]
SPDX-FileCopyrightText = [
    "2021-2026 Roy Shilkrot <roy.shil@gmail.com>",
    "2023-2026 Kaito Udagawa <umireon@kaito.tokyo>",
]
SPDX-License-Identifier = "CC0-1.0"
