# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: ORT CI

# file: .github/workflows/ort.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# version: 1.0.1
# date: 2026-04-02

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]
  schedule:
    - cron: 17 4 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-windows:
    permissions:
      contents: read
    uses: ./.github/workflows/ort-build-windows.yml
    with:
      VCPKG_BINARY_SOURCES: 'clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}'
      ort-version: v1.24.4

  build-macos:
    permissions:
      contents: read
    uses: ./.github/workflows/ort-build-macos.yml
    with:
      VCPKG_BINARY_SOURCES: 'clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}'
      ort-version: v1.24.4

  build-ubuntu:
    permissions:
      contents: read
    uses: ./.github/workflows/ort-build-ubuntu.yml
    with:
      VCPKG_BINARY_SOURCES: 'clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}'
      ort-version: v1.24.4

  accept-ort:
    name: Accept ORT CI
    needs: [build-windows, build-macos, build-ubuntu]
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Accept ort
        run: |
          echo 'The workflow ort has completed successfully.'
