# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

# file: plugin-release.yml
# author: Kaito Udagawa <umireon@kaito.tokyo>
# version: 1.0.0
# date: 2026-03-30

on:
  workflow_call:
    inputs:
      environment:
        description: The environment name for the release jobs, or empty string for no environment
        required: false
        type: string
        default: ''

jobs:
  create-draft-release:
    name: Create Draft Release

    if: startsWith(github.ref, 'refs/tags/')

    environment: ${{ inputs.environment }}
    runs-on: ubuntu-slim

    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Extract plugin buildspec
        id: buildspec
        uses: ./.github/actions/extract-buildspec

      - name: Select secure directory
        id: secure-dir
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        run: |
          printf 'ARTIFACTS_DIR=%s\n' "$(mktemp -d -p "$RUNNER_TEMP" artifacts.XXXXXXXXXX)" >> "$GITHUB_OUTPUT"

      - name: Download plugin binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: ${{ steps.buildspec.outputs.NAME }}-pluginbinary-*
          merge-multiple: true
          path: ${{ steps.secure-dir.outputs.ARTIFACTS_DIR }}

      - name: Attest plugin binary artifacts
        id: attest
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: ${{ steps.secure-dir.outputs.ARTIFACTS_DIR }}/*

      - name: Create a draft release with artifacts
        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
        env:
          ARTIFACTS_DIR: '${{ steps.secure-dir.outputs.ARTIFACTS_DIR }}'
          BUNDLE_PATH: '${{ steps.attest.outputs.bundle-path }}'
          GH_TOKEN: '${{ github.token }}'
        working-directory: ${{ steps.secure-dir.outputs.ARTIFACTS_DIR }}
        run: |
          # Output the existing release info, or create a new draft release if not exists.
          if ! gh release view "$GITHUB_REF_NAME"; then
            gh release create "$GITHUB_REF_NAME" --draft --notes-from-tag --title "$GITHUB_REF_NAME" --verify-tag
          fi

          ASSETS=("$BUNDLE_PATH")

          for f in "$ARTIFACTS_DIR"/*; do
            case "$f" in
            *-windows-x64.zip) ASSETS+=("$f#ZIP Binary for Windows (x64)") ;;
            *-windows-x64-pdb.zip) ASSETS+=("$f") ;;
            *-macos-universal.pkg) ASSETS+=("$f#PKG Binary for macOS (Universal)") ;;
            *-macos-universal.dSYM.tar.xz) ASSETS+=("$f") ;;
            *-x86_64-linux-gnu.deb) ASSETS+=("$f#DEB Binary for Ubuntu (x86_64)") ;;
            *-x86_64-linux-gnu-dbgsym.ddeb) ASSETS+=("$f") ;;
            esac
          done

          gh release upload "$GITHUB_REF_NAME" "${ASSETS[@]}" --clobber
