# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

name: Plugin CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-windows.yml
    with:
      VCPKG_BINARY_SOURCES: 'clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}'

  build-macos:
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-macos.yml
    with:
      codesign-enabled: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
      VCPKG_BINARY_SOURCES: 'clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}'
    secrets: inherit

  build-ubuntu:
    permissions:
      contents: read
    uses: ./.github/workflows/plugin-build-ubuntu.yml
    with:
      VCPKG_BINARY_SOURCES: 'clear;http,https://vcpkg-obs.kaito.tokyo/{name}/{version}/{sha}'

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build-windows
      - build-macos
      - build-ubuntu
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write
    uses: ./.github/workflows/plugin-release.yml
    with:
      environment: production-release
